### ISSUE TITLE
Clarification of usage after deprecation?

### ISSUE THREAD

**Issue by dougharris** [ryancrum/json-pretty-print.el#2]
I'm running GNU Emacs 24.3.1 and I can load json.el (v 1.3), but it contains no interactive functions and no mention of the string "pretty".

Please update the readme on this to give an example or details on which version of json.el introduces this.

**Comment by ryancrum** [comment]
Hi @dougharris,

The readme already contains a link to https://github.com/thorstadt/json.el/blob/master/json.el, which is required if you are not on emacs-trunk. However, I'd recommend grabbing json.el off of trunk and just using that, since it contains improved versions of the contents of json-pretty-print.el. (http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/json.el?h=trunk)

I will update the readme to be more explicit about versioning, and where you can get the current code.

**Comment by dougharris** [comment]
Thanks!
